### ISSUE TITLE
ICOsurance

### ISSUE THREAD

**Issue by xonixx** [breaktheblock/hackathon#11]
**Team name:** ICOsurance

**Github repo:** https://github.com/CMLTeam/ICOsurance

**Team members:** 

- @xonixx - Vlad Gubarkov
- @justrocknrolla - Sasha Shchetynin
- @vgorin - Basil Gorin
- @lyapen - Oleksii Potapenko

**Team leader:** @xonixx

**What problem are you trying to solve?:**

_The project is aimed to provide the insurance solution to ICO investors against possible losses due to cyber-attacks during the ICO process._
 
Nowadays lots of ICOs suffer from cyber-security attacks. To name a few during last days:
- Parity Multisig Wallet Hack that affected 3 ICOs ($30m investors' money loss)
- CoinDash crowdfunding hack ($7m of investors money went to attacker's wallet)

We propose the enhanced standard for smart-token contracts (on top of ERC20) that has an insurance logic built-in.

_What this project IS NOT_

- This is not an insurance to the possible loss due to market price changes (volatility)
- This is not an insurance against fraud/scam ICOs. It's responsibility of an investor to properly assess a project to invest in.

**Why do you think Blockchain/SmartContract may be the right approach?:**
- [Eating your own dog food](https://en.wikipedia.org/wiki/Eating_your_own_dog_food) - use blockchain itself to protect blockchain
- all the logic is implemented as smart contract and operates on crypto-currency only (no fiat) so no risks due to volatility involved

**API/DATA/Gadget you are thinking about using:** 
Ethereum, [ERC20](https://theethereum.wiki/w/index.php/ERC20_Token_Standard), mock data (real data in future).

**What area do you need help on?:**
Insurance specialists

**Comment by makoto** [comment]
@xonixx hi, looks like there are lots of standard token contracts which you probably borrowed from somewhere. Could you somehow comment which contracts are copied and which ones you wrote from scratch so we can focus on contracts you wrote?

**Comment by xonixx** [comment]
@makoto This is correct. We started from standard token in attempt to secure it with insurance logic. But then we understood that we've missed one detail - that token itself is not responsible for transforming ETH into the token (i.e. crowdsale process). So in fact we are working now on creating Insured Crowdsale contract and Insured token which will complement it and which will serve a function of reimbursement fund.
This is WiP. Hopefully more meaningful code will come very soon.

**Comment by makoto** [comment]
Running `truffle migrate` shows the following errors.

```
21:05:38-makoto~/work/breaktheblock/ICOsurance/truffle (master)$ truffle migrate
Compiling ./contracts/ConvertLib.sol...
Compiling ./contracts/ERC20.sol...
Compiling ./contracts/ERC20Insured.sol...
Compiling ./contracts/FixedSupplyInsuredToken.sol...
Compiling ./contracts/FixedSupplyToken.sol...
Compiling ./contracts/InsuredToken.sol...
Compiling ./contracts/MetaCoin.sol...
Compiling ./contracts/Migrations.sol...
Compiling ./contracts/PayableToken.sol...
Compiling ./contracts/Token.sol...
Compiling ./contracts/TokenInsurer.sol...
Writing artifacts to ./build/contracts

Using network 'development'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
  Migrations: 0x0eb20d0f4df8eba57889c58b690095ef744d2e98
Saving successful migration to network...
Saving artifacts...
Running migration: 2_deploy_contracts.js
/Users/makoto/.nvm/versions/node/v7.7.2/lib/node_modules/truffle/build/cli.bundled.js:36891
  throw new Error("Could not find artifacts for " + import_path + " from any sources");
  ^

Error: Could not find artifacts for ./ERC20Interface.sol from any sources
    at Resolver.require (/Users/makoto/.nvm/versions/node/v7.7.2/lib/node_modules/truffle/build/cli.bundled.js:36891:9)
    at ResolverIntercept.require (/Users/makoto/.nvm/versions/node/v7.7.2/lib/node_modules/truffle/build/cli.bundled.js:206022:32)
    at /Users/makoto/work/breaktheblock/ICOsurance/truffle/migrations/2_deploy_contracts.js:3:32
    at ContextifyScript.Script.runInContext (vm.js:32:29)
    at ContextifyScript.Script.runInNewContext (vm.js:38:15)
    at /Users/makoto/.nvm/versions/node/v7.7.2/lib/node_modules/truffle/build/cli.bundled.js:87008:14
    at tryToString (fs.js:448:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:435:12)

```

**Comment by makoto** [comment]
Could you move some of your issue description under README file of your repo like https://github.com/divsinghal/Claimless so that it helps judges to understand your code when they start reviewing your code?
